MOROCCAN_SOURCES = {
    "ar": {
        "display": "العربية",
        "sources": [
            {"name": "هسبريس", "url": "https://www.hespress.com/rss"},
            {"name": "المساء", "url": "https://www.almassae.ma/rss"},
            {"name": "الصباح", "url": "https://www.assabah.ma/rss"},
            {"name": "أخبار اليوم", "url": "https://akhbaralyom.ma/feed/"},
            {"name": "الأحداث المغربية", "url": "https://www.alakhbar.ma/rss"},
            {"name": "البيان", "url": "https://www.albayane.ma/rss"},
            {"name": "الاتحاد الاشتراكي", "url": "https://www.alittihad.ma/rss"},
            {"name": "العلم", "url": "https://www.elalam.ma/rss"},
            {"name": "التجديد", "url": "https://www.attajdid.ma/rss"},
            {"name": "المنعطف", "url": "https://www.almounaataf.ma/feed/"},
            {"name": "الحركة", "url": "https://www.alharaka.ma/rss"},
            {"name": "الوطن الآن", "url": "https://www.alwatanalan.ma/feed/"},
            {"name": "كش24", "url": "https://www.kech24.ma/rss"},
            {"name": "أحداث أنفو", "url": "https://www.ahdath.info/feed/"},
            {"name": "شاو بريس", "url": "https://www.chaouipress.com/feed/"},
            {"name": "برلمان.كوم", "url": "https://www.barlamane.com/feed/"},
            {"name": "مدار21", "url": "https://www.madar21.ma/feed/"},
            {"name": "الرياضية", "url": "https://www.arryadia.ma/rss"},
            {"name": "2M", "url": "https://www.2m.ma/rss"},
            {"name": "ميدي 1 تيفي", "url": "https://www.medi1tv.ma/rss"},
            {"name": "شوف تيفي", "url": "https://www.chouftv.ma/rss"},
            {"name": "إحاطة", "url": "https://www.ihatt.ma/feed/"},
            {"name": "أكادير 24", "url": "https://www.agadir24.ma/feed/"},
            {"name": "طنجة 24", "url": "https://www.tanger24.ma/feed/"},
            {"name": "فاس نيوز", "url": "https://www.fesnews.ma/feed/"},
            {"name": "مراكش نيوز", "url": "https://www.marrakechnews.ma/feed/"},
            {"name": "وجدة سيتي", "url": "https://www.oujdacity.net/feed/"},
            {"name": "الدار البيضاء الآن", "url": "https://www.casablancanow.ma/feed/"},
            {"name": "سوس 24", "url": "https://www.souss24.ma/feed/"},
            {"name": "تطوان 24", "url": "https://www.tetouan24.ma/feed/"},
            {"name": "الريف العميق", "url": "https://www.arifalamik.com/feed/"},
            {"name": "ناظور سيتي", "url": "https://www.nadorcity.com/feed/"},
            {"name": "الحسيمة بريس", "url": "https://www.alhoceimapress.ma/feed/"},
            {"name": "جرادة 24", "url": "https://www.jerada24.ma/feed/"},
            {"name": "تازة بريس", "url": "https://www.tazapress.ma/feed/"},
            {"name": "مكناس بريس", "url": "https://www.meknespress.ma/feed/"},
            {"name": "تاونات 24", "url": "https://www.taounate24.ma/feed/"},
            {"name": "العرائش نيوز", "url": "https://www.larachenews.ma/feed/"},
            {"name": "القنيطرة نيوز", "url": "https://www.kenitranews.ma/feed/"},
            {"name": "الجديدة 24", "url": "https://www.eljadida24.ma/feed/"},
            {"name": "آسفي بريس", "url": "https://www.safipress.ma/feed/"},
            {"name": "ورزازات نيوز", "url": "https://www.ouarzazatenews.ma/feed/"},
            {"name": "بني ملال بريس", "url": "https://www.benimellalpress.ma/feed/"},
            {"name": "خريبكة بريس", "url": "https://www.khouribgapress.ma/feed/"},
            {"name": "سطات نيوز", "url": "https://www.settatnews.ma/feed/"},
            {"name": "قلعة السراغنة بريس", "url": "https://www.kelaatpress.ma/feed/"},
            {"name": "اليوسفية نيوز", "url": "https://www.youssoufianews.ma/feed/"},
            {"name": "الصحراء المغربية", "url": "https://www.sahra24.ma/feed/"},
            {"name": "العيون سيتي", "url": "https://www.laayounecity.com/feed/"},
            {"name": "الداخلة بريس", "url": "https://www.dakhlapress.ma/feed/"},
            {"name": "كلميم بريس", "url": "https://www.guelmimpress.ma/feed/"},
            {"name": "تيزنيت 24", "url": "https://www.tiznit24.ma/feed/"},
            {"name": "تارودانت بريس", "url": "https://www.taroudantpress.ma/feed/"},
            {"name": "زاكورة نيوز", "url": "https://www.zagoranews.ma/feed/"},
            {"name": "الرشيدية بريس", "url": "https://www.errachidiapress.ma/feed/"},
            {"name": "تالوين بريس", "url": "https://www.talouinpress.ma/feed/"},
            {"name": "أخبار بلادي", "url": "https://www.akhbarblad.ma/feed/"},
            {"name": "المغرب 24", "url": "https://www.maghreb24.ma/feed/"},
            {"name": "صوت المغرب", "url": "https://www.sawtalmaghrib.ma/feed/"},
            {"name": "المغرب الآن", "url": "https://www.almaghribalan.ma/feed/"},
            {"name": "بوابة المغرب", "url": "https://www.portal-maghrib.ma/feed/"},
            {"name": "شمس نيوز المغرب", "url": "https://www.shmsnews.ma/feed/"},
            {"name": "صدى المغرب", "url": "https://www.sadamaghreb.ma/feed/"},
            {"name": "مشاهد", "url": "https://www.mochahid.ma/feed/"},
            {"name": "أخبارنا المغربية", "url": "https://www.akhbarona.ma/feed/"},
            {"name": "زين 24", "url": "https://www.zain24.ma/feed/"},
            {"name": "سياسة نيوز", "url": "https://www.siyassanews.ma/feed/"},
            {"name": "اقتصاد المغرب", "url": "https://www.iqtisadmaghrib.ma/feed/"},
            {"name": "رياضة المغرب", "url": "https://www.riyadrat.ma/feed/"},
            {"name": "فن المغرب", "url": "https://www.fanmaghrib.ma/feed/"},
            {"name": "صحيفة الناس", "url": "https://www.elnass.ma/feed/"},
            {"name": "مغرب الغد", "url": "https://www.maghribghad.ma/feed/"},
            {"name": "المعلومة", "url": "https://www.maelouma.ma/feed/"},
        ]
    },
    "fr": {
        "display": "Français",
        "sources": [
            {"name": "Le360", "url": "https://www.le360.ma/rss"},
            {"name": "Medias24", "url": "https://medias24.com/feed/"},
            {"name": "TelQuel", "url": "https://www.telquel.ma/feed"},
            {"name": "Le Desk", "url": "https://ledesk.ma/feed/"},
            {"name": "Le Site Info", "url": "https://www.lesiteinfo.com/feed/"},
            {"name": "Maroc Hebdo", "url": "https://www.maroc-hebdo.press.ma/feed"},
            {"name": "Challenge.ma", "url": "https://www.challenge.ma/feed/"},
            {"name": "La Vie Éco", "url": "https://www.lavieeco.com/feed/"},
            {"name": "Finances News", "url": "https://fnh.ma/feed/"},
            {"name": "L'Economiste", "url": "https://www.leconomiste.com/rss"},
            {"name": "Aujourd'hui Le Maroc", "url": "https://www.aujourdhui.ma/rss"},
            {"name": "Le Matin", "url": "https://www.lematin.ma/rss"},
            {"name": "Libération Maroc", "url": "https://www.libe.ma/rss"},
            {"name": "L'Opinion", "url": "https://www.lopinion.ma/rss"},
            {"name": "L'Observateur", "url": "https://www.lobservateur.ma/feed/"},
            {"name": "Atlasinfo", "url": "https://www.atlasinfo.fr/feed/"},
            {"name": "Yabiladi", "url": "https://www.yabiladi.com/articles/rss.xml"},
            {"name": "Bladi.net", "url": "https://www.bladi.net/rss.xml"},
            {"name": "H24Info", "url": "https://www.h24info.ma/feed/"},
            {"name": "Médias 24", "url": "https://www.medias24.ma/feed/"},
            {"name": "Boursier.ma", "url": "https://www.boursier.ma/rss"},
            {"name": "MAP Express", "url": "https://www.mapexpress.ma/feed/"},
            {"name": "Hespress Français", "url": "https://fr.hespress.com/feed/"},
            {"name": "Le Reporter", "url": "https://www.lereporter.ma/feed/"},
            {"name": "Panorapost", "url": "https://www.panorapost.ma/feed/"},
            {"name": "Made in Casablanca", "url": "https://www.madeincasablanca.ma/feed/"},
            {"name": "Fez City", "url": "https://www.fezcity.ma/feed/"},
            {"name": "Sahara Press Service", "url": "https://www.spsrasd.info/feed/"},
            {"name": "Maroc Diplomatique", "url": "https://www.maroc-diplomatique.net/feed/"},
            {"name": "Migrations & Développement", "url": "https://www.migdev.ma/feed/"},
            {"name": "Vivafrik", "url": "https://www.vivafrik.com/feed/"},
            {"name": "EcoActu", "url": "https://www.ecoactu.ma/feed/"},
            {"name": "Médias 24", "url": "https://www.medias24.com/feed/"},
            {"name": "Quid.ma", "url": "https://www.quid.ma/feed/"},
            {"name": "Le7tv", "url": "https://www.le7tv.ma/feed/"},
            {"name": "Radio 2M", "url": "https://www.2m.ma/rss/fr"},
            {"name": "Chouf TV", "url": "https://www.chouftv.ma/feed/fr"},
            {"name": "Medi1 Radio", "url": "https://www.medi1.com/feed/fr"},
            {"name": "Hit Radio", "url": "https://www.hitradio.ma/feed/"},
            {"name": "Radio Mars", "url": "https://www.radiomars.ma/feed/"},
            {"name": "MedRadio", "url": "https://www.medradio.ma/feed/"},
            {"name": "Atlantic Radio", "url": "https://www.atlanticradio.ma/feed/"},
            {"name": "Chada FM", "url": "https://www.chadafm.ma/feed/"},
            {"name": "Luxe Radio", "url": "https://www.luxeradio.ma/feed/"},
            {"name": "Agadir NET", "url": "https://www.agadirnet.ma/feed/"},
            {"name": "Maroc Tourisme", "url": "https://www.maroctourisme.ma/feed/"},
            {"name": "Hotel News", "url": "https://www.hotelnews.ma/feed/"},
            {"name": "Resto.ma", "url": "https://www.resto.ma/feed/"},
            {"name": "Maghreb Arabe Presse", "url": "https://www.mapnews.ma/feed/fr"},
            {"name": "Portail du Maroc", "url": "https://www.portaildumaroc.ma/feed/"},
            {"name": "Maghreb Info", "url": "https://www.maghreb-info.com/feed/"},
        ]
    },
    "en": {
        "display": "English",
        "sources": [
            {"name": "Morocco World News", "url": "https://www.moroccoworldnews.com/feed/"},
            {"name": "North Africa Post", "url": "https://northafricapost.com/feed/"},
            {"name": "The Africa Report", "url": "https://www.theafricareport.com/feed/"},
            {"name": "Afrik 21", "url": "https://www.afrik21.africa/feed/"},
            {"name": "Al Jazeera Africa", "url": "https://www.aljazeera.com/xml/rss/africa.xml"},
            {"name": "BBC Africa", "url": "https://feeds.bbci.co.uk/news/world/africa/rss.xml"},
            {"name": "France24 Africa", "url": "https://www.france24.com/en/africa/rss"},
            {"name": "CNN Africa", "url": "http://rss.cnn.com/rss/edition_africa.rss"},
            {"name": "Reuters Africa", "url": "https://www.reutersagency.com/feed/"},
            {"name": "AP Africa", "url": "https://rsshub.app/apnews/topics/apf-africa"},
            {"name": "The Guardian Africa", "url": "https://www.theguardian.com/world/africa/rss"},
            {"name": "DW Africa", "url": "https://rss.dw.com/xml/rss-en-africa"},
            {"name": "Quartz Africa", "url": "https://qz.com/africa/feed"},
            {"name": "Tech Morocco", "url": "https://www.techmorocco.ma/feed/"},
            {"name": "Invest in Morocco", "url": "https://www.investinmorocco.ma/feed/"},
            {"name": "Morocco Latest News", "url": "https://www.moroccolatestnews.com/feed/"},
            {"name": "Morocco on The Guardian", "url": "https://www.theguardian.com/world/morocco/rss"},
        ]
    }
}

def get_all_sources():
    all_sources = []
    for lang, lang_data in MOROCCAN_SOURCES.items():
        for s in lang_data["sources"]:
            all_sources.append({**s, "lang": lang})
    return all_sources

TOTAL_SOURCES = sum(len(v["sources"]) for v in MOROCCAN_SOURCES.values())
